import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ClerkProvider, SignedIn } from '@clerk/nextjs';
import { NavBar } from '@/components/NavBar';
import { SignOutButton } from '@clerk/nextjs';
import { InfoAboutUser } from '@/components/InfoAboutUser';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className=" flex flex-col  min-h-screen overflow-x-hidden">
          <SignedIn>
            <NavBar></NavBar>
            <InfoAboutUser></InfoAboutUser>
          </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
